syntax="proto3";
package order;

option go_package="github.com/niklvrr/OnlineShop/proto-contracts/gen/go/order";

service OrderService {
  rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);

  rpc GetAllOrders(GetAllOrdersRequest) returns (GetAllOrdersResponse);

  rpc GetOrderStatus(GetOrderStatusRequest) returns (GetOrderStatusResponse);
}

// ==== CREATE ORDER ====
message CreateOrderRequest {
  string user_id = 1;
  float amount = 2;
  string description = 3;
  string status = 4;
}

message CreateOrderResponse {
  string order_id = 1;
}

// ==== GET ALL ORDERS ====
message GetAllOrdersRequest {
  uint32 limit = 1;
  uint32 page = 2;
}

message GetAllOrdersResponse {
  repeated Order orders = 1;
}

message Order {
  string id = 1;
  string user_id = 2;
  float amount = 3;
  string description = 4;
  string status = 5;
}

// ==== GET ORDER STATUS ====
message GetOrderStatusRequest {
  string order_id = 1;
}

message GetOrderStatusResponse {
  string status = 2;
}