syntax = "proto3";

package payment;

option go_package="github.com/niklvrr/OnlineShop/proto-contracts/gen/go/payment";

service PaymentService {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse);

  rpc ReplenishAccount(ReplenishAccountRequest) returns (ReplenishAccountResponse);

  rpc GetBalance(GetBalanceRequest) returns (GetBalanceResponse);

  rpc DebitToAccount(DebitToAccountRequest) returns (DebitToAccountResponse);

  rpc GetAccountByUserId(GetAccountByUserIdRequest) returns (GetAccountByUserIdResponse);

  rpc InitiatePayment(InitiatePaymentRequest) returns (InitiatePaymentResponse);

  rpc GetPaymentStatus(GetPaymentStatusRequest) returns (GetPaymentStatusResponse);
}

// ==== CREATE ACCOUNT ====
message CreateAccountRequest {
  string user_id = 1;
}

message CreateAccountResponse {
  string account_id = 1;
}

// ==== REPLENISH ACCOUNT ====
message ReplenishAccountRequest {
  string account_id = 1;
  float replenish_amount = 2;
}

message ReplenishAccountResponse {
  string status = 1;
}

// ==== GET BALANCE ====
message GetBalanceRequest {
  string account_id = 1;
}

message GetBalanceResponse {
  float balance = 1;
}

// ==== DEBIT TO ACCOUNT ====
message DebitToAccountRequest {
  string account_id = 1;
  float debit_amount = 2;
}

message DebitToAccountResponse {
  string status = 1;
}

// ==== GET ACCOUNT BY USER ID ====
message GetAccountByUserIdRequest {
  string user_id = 1;
}

message GetAccountByUserIdResponse {
  string account_id = 1;
}

// ==== INITIATE PAYMENT ====
message InitiatePaymentRequest {
  string order_id = 1;
  string user_id = 2;
  float amount = 3;
  string payment_method = 4;
  string idempotency_key = 5;
}

message InitiatePaymentResponse {
  string payment_id = 1;
  string status = 2;
}

// ==== GET PAYMENT STATUS ====
message GetPaymentStatusRequest {
  string payment_id = 1;
}

message GetPaymentStatusResponse {
  string payment_id = 1;
  string order_id = 2;
  string status = 3;
  float amount = 4;
}